<?php

namespace App\Http\Requests\API;

use App\Models\EmpresaParametro;
use App\Http\Request\APIRequest;

class CreateEmpresaParametroAPIRequest extends APIRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return EmpresaParametro::$rules;
    }

    public function getValidatorInstance()
    {
        $data = $this->all();
        $empresa_id = $this->route('empresa_id') ? $this->route('empresa_id') : null;
        $data['empresa_id'] = $empresa_id;
        $this->getInputSource()->replace($data);
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }
}
